### ISSUE TITLE
AttributeError: 'module' object has no attribute 'write'

### ISSUE THREAD

**Issue by evandrocoan** [vishr/local-history#104]
Ok, can you believe what I am seeing here?
```python
Exception in thread Thread-896:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "F:\SublimeText\Data\Packages\LocalHistory\LocalHistory.py", line 204, in process_history
    sys.write.stderr('File History: File not saved, as it does not exists: %s\n' % file_path)
AttributeError: 'module' object has no attribute 'write'
```

I just had opened a new window. Why this package have so many unexplicable things happening?

1. FileNotFoundError: [WinError 2] The system cannot find the file specified #103
1. FileExistsError: [WinError 183] Cannot create a file when that file already exists #100

**Comment by evandrocoan** [comment]
Hey boy, it is not `sys.write.stderr`, it is `sys.stderr.write`
