### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rabinshr** [vishr/local-history#51]
I am getting the following error when trying to compare history for a file. I am using Sublime Text 3 beta

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'from_file'

**Comment by marcus-at-localhorst** [comment]
I am getting the same error
```
Traceback (most recent call last):
  File "E:\xampp\SublimeText\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'from_file'
```
