### ISSUE TITLE
Replacement doesn't work

### ISSUE THREAD

**Issue by Kristinita** [vishr/local-history#75]
Hello. I want to replace my working file with the file in the Local History folder. In my file Right mouse click → <kbd>Local History</kbd> → <kbd>Replace</kbd>, but changes nothing, but changes nothing. Traceback:

```
Traceback (most recent call last):
  File "LocalHistory in E:\Sublime Text 3\Data\Installed Packages\Local History.sublime-package", line 232, in on_done
  File "./python3.3/encodings/cp1251.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 20626: character maps to <undefined>
```

What do I have to make to carry out replacement? Thanks.

**Comment by jrappen** [comment]
@Kristinita please see if the latest updates resolve your issue, Package Control should update within the next hour or so.

**Comment by Kristinita** [comment]
@jrappen, unfortunately, replacement is not performed.
```
command: history_replace {"event": {"x": 935.5, "y": 568.5}}
Traceback (most recent call last):
  File "LocalHistory in E:\Sublime Text 3 Portable For Tests\Data\Installed Packages\Local History.sublime-package", line 241, in on_done
  File "E:\Sublime Text 3 Portable For Tests\sublime.py", line 710, in replace
    raise ValueError("Edit objects may not be used after the TextCommand's run method has returned")
ValueError: Edit objects may not be used after the TextCommand's run method has returned
```

**Comment by Kristinita** [comment]
@jrappen , actually in Build 3126

```
Traceback (most recent call last):
  File "LocalHistory in E:\Sublime Text Build 3126 For Debug\Data\Installed Packages\Local History.sublime-package", line 241, in on_done
  File "E:\Sublime Text Build 3126 For Debug\sublime.py", line 821, in replace
    raise ValueError("Edit objects may not be used after the TextCommand's run method has returned")
ValueError: Edit objects may not be used after the TextCommand's run method has returned
```

Thanks.
