### ISSUE TITLE
"File Not Found" error when browsing history of a file 

### ISSUE THREAD

**Issue by rhamzeh** [vishr/local-history#80]
When attempting to browse history of a file, a FileNotFoundError is thrown

````python
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 798, in run_
    return self.run(edit)
  File "{{SUBLIME_DIR}}/Packages/Local History/LocalHistory.py", line 164, in run
    subprocess.call('xdg-open %s' % target_dir)
  File "./python3.3/subprocess.py", line 523, in call
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open {{FILE_DIR}}'
````

OS: Linux
Distribution: Ubuntu
Release: 16.04.1 LTS (Xenial)
Sublime Text Version 3, Build 3119

**Comment by rhamzeh** [comment]
I believe this is a bug introduced in vishr/local-history#73
